spring.application.name=poplaki-mk-backend
spring.main.banner-mode=off

# management
management.endpoints.web.exposure.include=health,info,prometheus,metrics

# open api
springdoc.info.title=Complaint
springdoc.info.version=@project.version@
springdoc.api-docs.path=/api-docs
springdoc.packages-to-scan=mk.poplaki.controller

# MongoDB configuration
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/complaint}

security.jwt.access-token.secret-key=${JWT_ACCESS_KEY:VzzkQbnlEgjCmZseQHuVVvB94Ia7/a8gaYMk6ZFy0Kc=}
security.jwt.access-token.validity=${JWT_ACCESS_VALIDITY:1800000}
security.jwt.refresh-token.secret-key=${JWT_REFRESH_KEY:DN4tBr22Zzy7dHdWQI/bHD5fjccJiRZIX3lJv8mCMuU=}
security.jwt.refresh-token.validity=${JWT_REFRESH_VALIDITY:2592000000}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB